server:
  port: 9001
spring:
  application:
    name: localhost
  datasource:
    url: mysql地址
    username: mysql账号
    password: mysql密码
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
#    prefer-ip-address: true #在注册中心不显示ip的地址前缀
  client:
    serviceUrl:
      defaultZone:  http://eureka-server:8001/eureka/,http://eureka-server2:8002/eureka/,http://eureka-server3:8003/eureka/
      #defaultZone: http://eureka-server:8001/eureka/,http://eureka-server2:8002/eureka/,http://eureka-server3:8003/eureka/


