server:
  port: 8003

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
      routes:
      - id: frank_route
        uri: http://example.org
        predicates:
        - Path=/frank

